[View in Colaboratory](https://colab.research.google.com/github/lnarasimhan83/anzdemo/blob/master/Session2.ipynb)

In [20]:
import numpy as np
np.random.random((3,3))




array([[0.82958266, 0.64780523, 0.68588627],
       [0.10840272, 0.33798272, 0.57444253],
       [0.29309933, 0.97796407, 0.44605036]])

In [9]:
def quicksort(eip):
    if len(eip) <= 1:
        return eip
    pivot = eip[len(eip) // 2]
    left = [x for x in eip if x < pivot]
    middle = [x for x in eip if x == pivot]
    right = [x for x in eip if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [11]:
eip_in = 3
print(type(eip_in)) # Prints "<class 'int'>"
print(eip_in)       # Prints "3"
print(eip_in + 1)   # Addition; prints "4"
print(eip_in - 1)   # Subtraction; prints "2"
print(eip_in * 2)   # Multiplication; prints "6"
print(eip_in ** 2)  # Exponentiation; prints "9"
eip_in += 1
print(eip_in)  # Prints "4"
eip_in *= 2
print(eip_in)  # Prints "8"
eip = 2.5
print(type(eip)) # Prints "<class 'float'>"
print(eip, eip + 1, eip * 2, eip ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [13]:
eip_in = True
eip_out = False
print(type(eip_in)) # Prints "<class 'bool'>"
print(eip_in and eip_out) # Logical AND; prints "False"
print(eip_in or eip_out)  # Logical OR; prints "True"
print(not eip_in)   # Logical NOT; prints "False"
print(eip_in != eip_out)  # Logical XOR; prints "True

<class 'bool'>
False
True
False
True


In [2]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
eip = hello + ' ' + world  # String concatenation
print(eip)  # prints "hello world"
eip12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(eip12)  # prints "hello world 12"

hello
5
hello world
hello world 12


In [4]:
mlbr = "hello"
print(mlbr.capitalize())  # Capitalize a string; prints "Hello"
print(mlbr.upper())       # Convert a string to uppercase; prints "HELLO"
print(mlbr.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(mlbr.center(7))     # Center a string, padding with spaces; prints " hello "
print(mlbr.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [6]:
eip_list = [3, 1, 2]    # Create a list
print(eip_list, eip_list[2])  # Prints "[3, 1, 2] 2"
print(eip_list[-1])     # Negative indices count from the end of the list; prints "2"
eip_list[2] = 'foo'     # Lists can contain elements of different types
print(eip_list)         # Prints "[3, 1, 'foo']"
eip_list.append('bar')  # Add a new element to the end of the list
print(eip_list)         # Prints "[3, 1, 'foo', 'bar']"
mlbr_out = eip_list.pop()      # Remove and return the last element of the list
print(mlbr_out, eip_list)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [8]:
eip_list = list(range(5))     # range is a built-in function that creates a list of integers
print(eip_list)               # Prints "[0, 1, 2, 3, 4]"
print(eip_list[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(eip_list[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(eip_list[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(eip_list[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(eip_list[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
eip_list[2:4] = [8, 9]        # Assign a new sublist to a slice
print(eip_list)               # Prints "[0, 1, 8, 9, 4]

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [10]:

eips = ['cat', 'dog', 'monkey']
for eip in eips:
    print(eip)
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


In [12]:
mlblrs = ['cat', 'dog', 'monkey']
for idx, mlblr in enumerate(mlblrs):
    print('#%d: %s' % (idx + 1, mlblr))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own lin

#1: cat
#2: dog
#3: monkey


In [13]:
mlbr_in = [0, 1, 2, 3, 4]
squares = []
for x in mlbr_in:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [14]:
mlbr = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in mlbr]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [15]:
mlbr = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in mlbr if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


In [22]:
eip_dict = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(eip_dict['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in eip_dict)     # Check if a dictionary has a given key; prints "True"
eip_dict['fish'] = 'wet'     # Set an entry in a dictionary
print(eip_dict['fish'])      # Prints "wet"
# print(eip_dict['monkey'])  # KeyError: 'monkey' not a key of d
print(eip_dict.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(eip_dict.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del eip_dict['fish']         # Remove an element from a dictionary
print(eip_dict.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


In [26]:

mlbr = {'person': 2, 'cat': 4, 'spider': 8}
for animal in mlbr:
    legs = mlbr[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [27]:

eip = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in eip if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}

{0: 0, 2: 4, 4: 16}


In [29]:
mlbr = {'cat', 'dog'}
print('cat' in mlbr)   # Check if an element is in a set; prints "True"
print('fish' in mlbr)  # prints "False"
mlbr.add('fish')       # Add an element to a set
print('fish' in mlbr)  # Prints "True"
print(len(mlbr))       # Number of elements in a set; prints "3"
mlbr.add('cat')        # Adding an element that is already in the set does nothing
print(len(mlbr))       # Prints "3"
mlbr.remove('cat')     # Remove an element from a set
print(len(mlbr))       # Prints "2"

True
False
True
3
3
2


In [30]:
eip_dict = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(eip_dict):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: cat
#3: dog


In [31]:
from math import sqrt
eip = {int(sqrt(x)) for x in range(30)}
print(eip)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


In [32]:
eip = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
mlbr = (5, 6)        # Create a tuple
print(type(mlbr))    # Prints "<class 'tuple'>"
print(eip[mlbr])       # Prints "5"
print(eip[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


In [33]:
def mlbr_out(mlbr_in):
    if mlbr_in > 0:
        return 'positive'
    elif mlbr_in < 0:
        return 'negative'
    else:
        return 'zero'

for mlbr_in in [-1, 0, 1]:
    print(mlbr_out(mlbr_in))
# Prints "negative", "zero", "positive"

negative
zero
positive


In [34]:
def eip(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

eip('Bob') # Prints "Hello, Bob"
eip('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


In [35]:
class mlbr(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def eip(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = mlbr('Fred')  # Construct an instance of the Greeter class
g.eip()            # Call an instance method; prints "Hello, Fred"
g.eip(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


In [37]:
import numpy as np

eip = np.array([1, 2, 3])   # Create a rank 1 array
print(type(eip))            # Prints "<class 'numpy.ndarray'>"
print(eip.shape)            # Prints "(3,)"
print(eip[0], eip[1], eip[2])   # Prints "1 2 3"
eip[0] = 5                  # Change an element of the array
print(eip)                  # Prints "[5, 2, 3]"

mlbr = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(mlbr.shape)                     # Prints "(2, 3)"
print(mlbr[0, 0], mlbr[0, 1], mlbr[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [39]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
eip = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
mlbr = eip[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(eip[0, 1])   # Prints "2"
mlbr[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(eip[0, 1])   # Prints "77"

2
77


In [41]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
eip_in1 = a[1, :]    # Rank 1 view of the second row of a
eip_in2 = a[1:2, :]  # Rank 2 view of the second row of a
print(eip_in1, eip_in1.shape)  # Prints "[5 6 7 8] (4,)"
print(eip_in2, eip_in2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
mlbr_in1 = a[:, 1]
mlbr_in2 = a[:, 1:2]
print(mlbr_in1, mlbr_in1.shape)  # Prints "[ 2  6 10] (3,)"
print(mlbr_in2, mlbr_in2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [42]:
import numpy as np

eip = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(eip[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([eip[0, 0], eip[1, 1], eip[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(eip[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([eip[0, 1], eip[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [43]:
import numpy as np

# Create a new array from which we will select elements
mlbr_in = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
mlbr_out = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(mlbr_in[np.arange(4), mlbr_out])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
mlbr_in[np.arange(4), mlbr_out] += 10

print(mlbr_in)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [44]:
import numpy as np

mlbr_out = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (mlbr_out > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(mlbr_out[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(mlbr_out[mlbr_out > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [46]:
import numpy as np

eip = np.array([1, 2])   # Let numpy choose the datatype
print(eip.dtype)         # Prints "int64"

eip = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(eip.dtype)             # Prints "float64"

eip = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(eip.dtype)                         # Prints "int64"

int64
float64
int64


In [47]:
import numpy as np

eip = np.array([[1,2],[3,4]], dtype=np.float64)
mlbr = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(eip + mlbr)
print(np.add(eip, mlbr))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(eip - mlbr)
print(np.subtract(eip, mlbr))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(eip * mlbr)
print(np.multiply(eip, mlbr))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(eip / mlbr)
print(np.divide(eip, mlbr))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(eip))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [48]:
import numpy as np

eip_in = np.array([[1,2],[3,4]])
eip_out = np.array([[5,6],[7,8]])

mlbr_in = np.array([9,10])
mlbr_out = np.array([11, 12])

# Inner product of vectors; both produce 219
print(mlbr_in.dot(mlbr_out))
print(np.dot(mlbr_in, mlbr_out))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(eip_in.dot(mlbr_out))
print(np.dot(eip_in, mlbr_out))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(eip_in.dot(eip_out))
print(np.dot(eip_in, eip_out))

219
219
[35 81]
[35 81]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [50]:
import numpy as np

eip = np.array([[1,2],[3,4]])

print(np.sum(eip))  # Compute sum of all elements; prints "10"
print(np.sum(eip, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(eip, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [49]:
import numpy as np

eip = np.array([[1,2], [3,4]])
print(eip)    # Prints "[[1 2]
            #          [3 4]]"
print(eip.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
eip_in = np.array([1,2,3])
print(eip_in)    # Prints "[1 2 3]"
print(eip_in.T)  # Prints "[1 2 3]

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [53]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
mlbr = np.array([1, 0, 1])
mlbr1 = np.empty_like(eip)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    mlbr1[i, :] = eip[i, :] + mlbr

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(mlbr1)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [56]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip1 = np.array([1, 0, 1])
eip2 = np.empty_like(eip)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    eip2[i, :] = eip[i, :] + eip1

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(eip2)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [57]:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
eip = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
eip1 = np.array([1, 0, 1])
eip2 = eip + eip1  # Add v to each row of x using broadcasting
print(eip2)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
import numpy as np

# Compute outer product of vectors
eip = np.array([1,2,3])  # v has shape (3,)
eip1 = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(eip, (3, 1)) * eip1)

# Add a vector to each row of a matrix
eip2 = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(eip2 + eip)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((eip2.T + eip1).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(eip2 + np.reshape(eip1, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(eip2 * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [60]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)

FileNotFoundError: ignored

In [62]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

# Create the following array where each row is a point in 2D space:
# [[0 1]
#  [1 0]
#  [2 0]]
eip = np.array([[0, 1], [1, 0], [2, 0]])
print(eip)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
eip = squareform(pdist(x, 'euclidean'))
print(eip )

[[0 1]
 [1 0]
 [2 0]]
[[0.         5.19615242]
 [5.19615242 0.        ]]
